### ISSUE TITLE
Missing `react-dom/server`

### ISSUE THREAD

**Issue by rauchg** [NervJS/nerv#11]
I believe for `nerv` to be a _true drop-in replacement_ it would have to implement the equivalent of `react-dom/server`:

![image](https://user-images.githubusercontent.com/13041/34794861-e68ca210-f604-11e7-9cc6-35d892868ff1.png)

**Comment by luckyadam** [comment]
Hey bro,you should install the package `nerv-server`

**Comment by rauchg** [comment]
Does that populate ‘nervjs/server’? It would be nice if it was the same API as react-dom, down to the require call

**Comment by yuche** [comment]
@rauchg 
It's a little bit tricky to populate `nervjs/server`,  since Nerv is a monorepo repo that manage by [lerna](https://github.com/lerna/lerna), which means the server render part will be publish separately from the `nervjs`.

Although we can copy `nerv-server` built files to `nervjs` dist folder, this will do the trick.

**Comment by georgiemathews** [comment]
I'm getting the following when running the production build, I tried moving the nerv-server to nervjs as well as aliasing nervjs/server to nerv-server
```
Error: Next.js 4 requires React 16.
Install React 16 with:
```

**Comment by 23hp** [comment]
can i use gatsbyjs with nerv now ?  what about this plugin
https://www.npmjs.com/package/gatsby-plugin-nerv
能和gatsbyjs项目中用吗，使用上面这个插件？
