### ISSUE TITLE
[RFC]: 使用 lerna 重构组织项目结构

### ISSUE THREAD

**Issue by yuche** [NervJS/nerv#2]
现在 Nerv 和 preact  一样，compat, ssr, redux, test-utils 等分开在不同的仓库。这些天的开发目前有几个痛点：

1. 有时候多个组件同时依赖一些内部方法，例如 `isWidget()`，导致每个仓库都要维护一份这个方法。同时打包出来也每个包都有一个；
2. 当 Nerv 更新时不能确定其他下属包还能不能兼容；
3. 同时开几个项目时编辑器转来转去太麻烦；
4. 各个包依赖基本都是相同的，有时候依赖包出问题或者要更新（例如修改.babelrc）又要几个包分开更新

[Lerna](https://github.com/lerna/lerna) 就能很好地解决这些问题，除上述问题之外还提供 change log 自动生成的功能和统一管理 semver，这样多人维护和解决历史 bug 就可以少翻 commit history 和 git blame 了。

现在三大框架 react, angular, vue 和一些大型前端项目例如 babel 也都在用，至少看起来也专业不少。~~另外这样也能 star 聚拢起来而不是分散到各个 repo，万一我们火了呢~~ ：）

**Comment by t47io** [comment]
Translation:

## [RFC] Refactor code structure using lerna

Currently nerv is similar to preact in the way that compat, ssr, redux, test-utils, etc. are in separate repositories. This makes some pain points:

1. When multiple component sharing the same internal method, e.g. isWidget(), each repository needs to maintain its own copy. Also each project contains a copy of the same method in the bundle.
2. When updating nerv, we are unsure if it remains fully compatible with the associated projects.
3. Too much overhead to open and switch between multiple projects in text editor.
4. The dependencies of projects are very similar to each other. Thus it takes repeated effort to update a dependency (e.g. editing .babelrc).

lerna can solve these problems well. In addition, it enables auto-generation of change log and managing semver. Thus it takes less of digging through commit history or git blame to maintain codebase or solve long-standing bugs.

Now react, angular, vue and other mainstream front-end projects (e.g. babel) are all using lerna. ~~ Also we can have all the stars at one repository instead of scattered to several, what if nerv becomes popular. ~~
