### ISSUE TITLE
nerv-test-utils package is missing files

### ISSUE THREAD

**Issue by mgroenhoff** [NervJS/nerv#27]
I tried to install `nerv-test-utils` to replace `react-dom/test-utils` but it seems that the package does not contain all of the source files. The `index.js` tried to require `./src/index.js` but the entire `src` folder is excluded from packaging in `.npmignore`.

**Comment by yuche** [comment]
The problem have been fixed in version `1.2.5-beta.3`.
Noted that what Nerv's implementation is like the way [React 16 did](https://reactjs.org/docs/test-utils.html#overview), below API is included:

* Simulate
* renderIntoDocument
* mockComponent
* isElement
* isElementOfType
* isDOMComponent
* isDOMComponentOfType
* isCompositeComponent
* isCompositeComponentWithType
* findAllInRenderedTree
* scryRenderedDOMComponentsWithClass
* scryRenderedComponentsWithType
* scryRenderedDOMComponentsWithTag
* findRenderedComponentWithType
* findRenderedDOMComponentWithClass
* findRenderedDOMComponentWithTag
